# Generated by Django 2.2.2 on 2019-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='id', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
