
CREATE TABLE user (
ID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
Role VARCHAR(20) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE todolist (
ID INT NOT NULL AUTO_INCREMENT,
Title VARCHAR(80) NOT NULL,
Due_Date DATE NOT NULL,
Priority ENUM('1', '2', '3'), 
PRIMARY KEY (ID));

CREATE TABLE milestone (
    ID INT NOT NULL AUTO_INCREMENT,
    Task_ID INT NOT NULL,
    Description VARCHAR(200),
    Status ENUM('Incomplete', 'In Progress', 'Complete'),
    ordering TINYINT NOT NULL,
    PRIMARY KEY (ID, task_ID),
    FOREIGN KEY (task_ID) REFERENCES todolist(ID) ON DELETE CASCADE);


