CREATE TABLE student (
ID SERIAL NOT NULL,
Name VARCHAR(20) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE parent (
ID SERIAL NOT NULL,
Name VARCHAR(20) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE mentor (
ID SERIAL NOT NULL,
Name VARCHAR(20) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE todolist (
Title VARCHAR(250) NOT NULL,
Content VARCHAR(250),
DUE_DATE DATE NOT NULL,
PRIMARY KEY (Title));
