
CREATE TABLE user (
ID SERIAL NOT NULL,
Name VARCHAR(50) NOT NULL,
Role VARCHAR(20) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE todolist (
ID SERIAL NOT NULL,
Title VARCHAR(80) NOT NULL,
Due_Date DATE NOT NULL,
Completed TINYINT(1),
In_Progress TINYINT(1),
Priority_Low TINYINT, 
Priority_High TINYINT,
Milestone TEXT,
PRIMARY KEY (ID),
FOREIGN KEY (user_id) REFERENCES user(ID)
ON DELETE CASCADE);

