-- INSERT INTO spr_user (name, role) VALUES
--     ('Dan Zhou', 'mentor'),
--     ('Laney Johnson', 'parent'),
--     ('Amaya Grant', 'parent'),
--     ('Aniyah Quigley', 'parent'),
--     ('Aileen Rohan', 'parent'),
--     ('Darion Cronin', 'student'),
--     ('Melissa Mitchell', 'student'),
--     ('Maxine Crona', 'student'),
--     ('Justice Adams', 'student');

INSERT INTO task (title, due_date, priority, sub_task, status, parent_task_id) VALUES
    ('UC Application', '2019-11-30', 'High', NULL, NULL, NULL),
    ('Common App', '2020-1-10', 'Low', NULL, NULL, NULL),
    ('Send out Email to Teachers', '2019-07-17', 'Low', NULL, 'Complete', Null),
    (NULL, NULL, NULL, 'Finalize majors and colleges', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Create Portal Log In', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Filling out personal information and activities', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Personal statement 1', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Personal statement 2', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Personal statement 3', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Personal statement 4', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Additional Comments', 'Incomplete', 1),
    (NULL, NULL, NULL, 'Finalize majors and colleges', 'Incomplete', 2),
    (NULL, NULL, NULL, 'Create Portal Log In', 'Incomplete', 2),
    (NULL, NULL, NULL, 'Assign and request letters of recommendations and approval', 'Incomplete', 2),
    (NULL, NULL, NULL, 'Filling out personal information and activites', 'Incomplete', 2),
    (NULL, NULL, NULL, 'Complete 650 common app essay', 'Incomplete', 2),
    (NULL, NULL, NULL, 'Complete college Supplements', 'Incomplete', 2),
    (NULL, NULL, NULL, 'Additional Comments', 'Incomplete', 2);
