# Generated by Django 2.2.2 on 2019-07-18 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_column='id', max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=500)),
                ('due_date', models.DateField(db_column='due_date', null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_column='priority', max_length=20, null=True)),
                ('sub_task', models.CharField(db_column='sub_task', max_length=500)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('In Progress', 'In Progress'), ('Complete', 'Completed')], db_column='status', max_length=30, null=True)),
                ('parent_task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.Task')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
