# Generated by Django 2.2.2 on 2019-07-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_column='id', max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('due_date', models.DateField(db_column='due_date')),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], db_column='priority')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Task_Milestones',
            fields=[
                ('id', models.CharField(db_column='id', max_length=8, primary_key=True, serialize=False)),
                ('milestone', models.CharField(db_column='milestone', max_length=200)),
                ('status', models.IntegerField(choices=[('0', 'Incomplete'), ('1', 'In Progress'), ('2', 'Completed')], db_column='status', default='0')),
                ('task_id', models.ForeignKey(db_column='task_id', max_length=8, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
            options={
                'db_table': 'task_milestone',
                'ordering': ['task_id', 'id'],
                'unique_together': {('id', 'task_id')},
            },
        ),
    ]
