# Generated by Django 2.2.2 on 2019-06-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.CharField(db_column='id', max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('due_date', models.DateField(default='2019-06-18')),
                ('completed', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todolist',
                'managed': False,
            },
        ),
    ]
