# Generated by Django 2.2.2 on 2019-07-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], db_column='priority', max_length=1),
        ),
        migrations.AlterField(
            model_name='task_milestones',
            name='status',
            field=models.CharField(choices=[('0', 'Incomplete'), ('1', 'In Progress'), ('2', 'Completed')], db_column='status', default='0', max_length=1),
        ),
    ]
