# Generated by Django 2.2.2 on 2019-06-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='content',
        ),
    ]
