# Generated by Django 2.2.2 on 2019-07-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent_task_id',
            new_name='parent_task',
        ),
    ]
