# Generated by Django 2.2.2 on 2019-07-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190718_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_task',
            field=models.CharField(db_column='sub_task', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_column='title', max_length=500, null=True),
        ),
    ]
