# Generated by Django 2.2.2 on 2019-06-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(db_column='name', max_length=20),
        ),
    ]
