# Generated by Django 2.2.2 on 2019-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(db_column='name', max_length=20),
        ),
    ]
